<?php                                                                                                                                                                                                                                                          
//Namespace our code for our application                                                                                                                                                                                                                       
namespace TDW\Theme;                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
//Include our Constants namespace                                                                                                                                                                                                                              
use \TDW\Theme\Constants as Constants;                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
//Instantiate our class                                                                                                                                                                                                                                        
class Core {                                                                                                                                                                                                                                                   
    /**********************************************************************************                                                                                                                                                                        
     * Initializes our theme (templates, hooks, filters, etc)                                                                                                                                                                                                  
     * ********************************************************************************/                                                                                                                                                                       
    public function __construct(){                                                                                                                                                                                                                             
        //Initialize our theme constants                                                                                                                                                                                                                       
        $this->constants = new Constants();                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                               
        //Init theme options                                                                                                                                                                                                                                   
        $this->version_check();                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                               
        //Add support for various WordPress features in this theme                                                                                                                                                                                             
        $this->add_theme_support();                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                               
    /***}*******************************************************************************                                                                                                                                                                       
     * Verifies we are running the minimum version of WordPress                                                                                                                                                                                                
     * ********************************************************************************/                                                                                                                                                                       
    public function version_check(){                                                                                                                                                                                                                           
        if (version_compare($GLOBALS['wp_version'], $this->constants->appMinWPVer, '<')) {                                                                                                                                                                     
            //TODO: Load version check template                                                                                                                                                                                                                
            //require get_template_directory().'';                                                                                                                                                                                                             
        }                                                                                                                                                                                                                                                      
    }                                                                                                                                                                                                                                                          
    /***}*******************************************************************************                                                                                                                                                                       
     * Adds supported theme features                                                                                                                                                                                                                           
     * ********************************************************************************/                                                                                                                                                                       
    public function add_theme_support(){                                                                                                                                                                                                                       
        //Add general theme support                                                                                                                                                                                                                            
        add_theme_support($this->constants->themeSupports);                                                                                                                                                                                                    
    }                                                                                                                                                                                                                                                          
}                                                                                                                                                                                                                                                              
